name: Build and Push Frontend Image

on:
  push:
    branches:
      - master
    paths:
      - 'IzvorniKod/**'      # Pokreće se samo za promene u /IzvorniKod direktorijumu
  workflow_dispatch:

jobs:
  build-and-push-frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-latest
    env:
      FRONTEND_DEPLOY_HOOK: ${{ secrets.FRONTEND_DEPLOY_HOOK }}
      REPOSITORY_NAME: ${{ github.repository }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME_LOWER=$(echo $REPOSITORY_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: 'IzvorniKod/yarn.lock'

      - name: Yarn install
        run: yarn install
        working-directory: IzvorniKod

      - name: Yarn build
        run: yarn run build
        working-directory: IzvorniKod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./IzvorniKod
          push: true
          tags: ghcr.io/${{ env.REPO_NAME_LOWER }}/frontend:latest

      - name: Trigger release
        if: ${{ env.FRONTEND_DEPLOY_HOOK }}
        run: curl ${{ env.FRONTEND_DEPLOY_HOOK }}
